### ISSUE TITLE
Royal Champion light doesn't work

### ISSUE THREAD

**Issue by toomoor** [boludoz/AIO-Mod#78]
my account is TH 14 and Royal Champion light doesn't work and still white color.
when bot check troops for ready to attack but have issues because my royal champion upgrading, bot thinking healing.
pls fix it. thanks

**Comment by toomoor** [comment]
fixed in update 4.9.6

**Comment by boludoz** [comment]
Fixed in v4.9.8 bro

**Comment by toomoor** [comment]
Gz

**Comment by toomoor** [comment]
still have issues 
![image](https://user-images.githubusercontent.com/46858785/162615419-97d43164-4b94-4d5d-8552-72c913c64ac9.png)
